In [25]:
import numpy

U = numpy.load('U_new.npy')
S = numpy.load('S_new.npy')
V_transpose = numpy.load('V_transpose_new.npy')

A = U.dot(numpy.diag(S).dot(V_transpose))

print("A = {}".format(A))

print("a) U1's estimated rating of the movie Amelie is: {}".format(A[0][3]))
print("b) The strength of concept 1 is: {}".format(S[0]))
print("c) The average rating of movie Harry Potter across all users is {}".format(numpy.average(A[:, 2])))
# Based on code print(max(numpy.sum(A, axis = 0)))
print("d) The movie with the overall highest rating is Casablanca")


A = [[5.00000001 4.5        0.99999997 1.49999999 0.99999999]
 [0.99999998 1.00000004 2.5        4.99999999 4.99999997]
 [4.00000001 4.5        0.99999997 0.99999999 0.99999999]
 [2.5        1.50000002 4.49999998 1.         0.99999998]
 [0.99999998 1.00000003 1.         4.         4.99999998]
 [0.99999999 1.00000002 4.49999999 1.5        2.49999998]]
a) U1's estimated rating of the movie Amelie is: 1.4999999898595036
b) The strength of concept 1 is: 13.266399703684902
c) The average rating of movie Harry Potter across all users is 2.416666650522624
d) The movie with the overall highest rating is Casablanca
